dist: bionic
language: python
python:
  - "3.6"

before_install:
  - ./install.sh
  - export PATH=$PATH:$PWD/
  - xsv --version
  - pip install requests

script:
  - mkdir output
  - wget https://www.data.gouv.fr/fr/datasets/r/50625621-18bd-43cb-8fde-6b8c24bdabb3 --no-verbose --output-document=opendata_irve.csv 2>&1
  - python compute_osm_stats.py
  - python group_opendata_by_station.py
  #fail if less than 2 lines
  - test `cat output/opendata_stations.csv | xsv count` -ge 2
  - cat output/opendata_stations.csv |xsv select n_operateur,n_enseigne |xsv sort |uniq > output/opendata_networks.csv

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_DEPLOY_TOKEN
  local_dir: output
  keep_history: true
  on:
    branch: master
